name: simple_deployment_pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Installe dependencies
        run: npm install
      - name: check styles
        run: npm run eslint
